sudo: false
language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
install:
  - if [[ "${TRAVIS_SCALA_VERSION}" == "2.10.6" ]]; then TEST_SBT_PLUGIN=true; else TEST_SBT_PLUGIN=false; fi
  # The default ivy resolution takes way too much time, and times out Travis builds.
  # We use coursier instead.
  - mkdir -p $HOME/.sbt/0.13/plugins/
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC3")' > $HOME/.sbt/0.13/plugins/coursier.sbt
script:
  - phantomjs -v
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-phantomjs/test scalajs-env-phantomjs/doc
  - |
      if [[ "${TEST_SBT_PLUGIN}" == "true" ]]; then
        sbt scalajs-env-phantomjs/publishLocal sbt-scalajs-env-phantomjs/publishLocal && \
        cd sbt-plugin-test && \
        sbt jetty9/run && \
        cd ..
      fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
  - rm $HOME/.sbt/0.13/plugins/coursier.sbt
